#pragma once

#include <stdint.h>

#define AODV_EN_PROTOCOL_VERSION              1u

#define AODV_EN_MAC_ADDR_LEN                  6u

#define AODV_EN_NEIGHBOR_TABLE_SIZE_DEFAULT   16u
#define AODV_EN_ROUTE_TABLE_SIZE_DEFAULT      32u
#define AODV_EN_RREQ_CACHE_SIZE_DEFAULT       64u
#define AODV_EN_PEER_CACHE_SIZE_DEFAULT       8u

#define AODV_EN_CONTROL_PAYLOAD_MAX_DEFAULT   128u
#define AODV_EN_DATA_PAYLOAD_MAX_DEFAULT      1024u

#define AODV_EN_MAX_HOPS_DEFAULT              16u
#define AODV_EN_TTL_DEFAULT                   16u

#define AODV_EN_NEIGHBOR_TIMEOUT_MS_DEFAULT   15000u
#define AODV_EN_ROUTE_LIFETIME_MS_DEFAULT     30000u
#define AODV_EN_RREQ_CACHE_TIMEOUT_MS_DEFAULT 10000u
#define AODV_EN_ACK_TIMEOUT_MS_DEFAULT        1000u

#define AODV_EN_RREQ_RETRY_COUNT_DEFAULT      3u
#define AODV_EN_LINK_FAIL_THRESHOLD_DEFAULT   3u

#define AODV_EN_ROUTE_METRIC_INFINITY         0xFFFFu

#ifndef AODV_EN_NEIGHBOR_TABLE_SIZE
#define AODV_EN_NEIGHBOR_TABLE_SIZE AODV_EN_NEIGHBOR_TABLE_SIZE_DEFAULT
#endif

#ifndef AODV_EN_ROUTE_TABLE_SIZE
#define AODV_EN_ROUTE_TABLE_SIZE AODV_EN_ROUTE_TABLE_SIZE_DEFAULT
#endif

#ifndef AODV_EN_RREQ_CACHE_SIZE
#define AODV_EN_RREQ_CACHE_SIZE AODV_EN_RREQ_CACHE_SIZE_DEFAULT
#endif

#ifndef AODV_EN_PEER_CACHE_SIZE
#define AODV_EN_PEER_CACHE_SIZE AODV_EN_PEER_CACHE_SIZE_DEFAULT
#endif

#ifndef AODV_EN_CONTROL_PAYLOAD_MAX
#define AODV_EN_CONTROL_PAYLOAD_MAX AODV_EN_CONTROL_PAYLOAD_MAX_DEFAULT
#endif

#ifndef AODV_EN_DATA_PAYLOAD_MAX
#define AODV_EN_DATA_PAYLOAD_MAX AODV_EN_DATA_PAYLOAD_MAX_DEFAULT
#endif
